-- This migration previously set admin password to plaintext (development only).
-- Passwords are now stored as SHA-256 base64 hashes.
-- To reset the admin password, run:
--
--   UPDATE users
--   SET password_hash = encode(digest('YOUR_NEW_PASSWORD', 'sha256'), 'base64')
--   WHERE email = 'admin@3cplus.com';
