# ❌ DESABILITADO: Edge Functions desnecessárias - usando apenas Render
# 
# Este keepalive chamava Edge Functions do Supabase que geravam custos altos
# Agora usando apenas Render para o servidor Socket2Webhook 24/7
#
# name: Webhook Keepalive (DISABLED)
#
# on:
#   schedule:
#     - cron: '*/5 * * * *'  # Era 288 calls/dia = custos altos
#   workflow_dispatch:
#
# jobs:
#   keepalive:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Edge Functions disabled
#       run: echo "Edge Functions desabilitadas - usando apenas Render"
